### ISSUE TITLE
Polyline 如果一开始points设置为空数组，会有baidu的api报错，之后添加值，会有vue3的报错

### ISSUE THREAD

**Issue by xwnwho** [lunnlew/baidu-map#10]
示例：https://github.com/xwnwho/vite2-vue3-ts-template/tree/baidu-map
报错：
![image](https://user-images.githubusercontent.com/80031313/154878096-5e139014-4851-4943-9291-4e2aee896a7d.png)
![image](https://user-images.githubusercontent.com/80031313/154878336-de6227fe-6920-43e3-a5db-d8a8ad7f817a.png)

**Comment by lunnlew** [comment]
嗯，百度地图Polyline初始化的时候，必须提供点集的。看一下需不需要优化，先修复了点集追加变更

**Comment by xwnwho** [comment]
好的，目前我手动设置init
