### ISSUE TITLE
太棒了，有这么好的baidumap插件，在用vite + ssg插件打包时候报错了

### ISSUE THREAD

**Issue by leosin** [lunnlew/baidu-map#4]
![image](https://user-images.githubusercontent.com/3676670/150951220-cff0f2f3-249c-4de9-a651-9a186e45bb43.png)

如图，当用在vite打包，并配合vite-ssg插件生成静态页面的时候，出现如上提示。

**Comment by lunnlew** [comment]
更改了构建的产出物，可以升级至0.4.1，问题应该修复了

**Comment by leosin** [comment]
> 更改了构建的产出物，可以升级至0.4.1，问题应该修复了

测试过了，0.4.1完美运行，赞👍 ！！顺便问一下，能否写一些示例，比如想增加覆盖物，窗口信息什么的，或者鼠标事件之类的，不知道正确的写法是什么样的。

**Comment by lunnlew** [comment]
嗯，事件使用@event方式，文档有空的话需要慢慢完善
