### ISSUE TITLE
vite打包类型校验通不过， vue tsc --noEmit

### ISSUE THREAD

**Issue by xwnwho** [lunnlew/baidu-map#5]
![微信截图_20220217154300](https://user-images.githubusercontent.com/80031313/154428724-50caa4a3-35c7-44cd-aeae-64d8e8a78072.png)

tsconfig 配置了exclude和skipLibCheck都不行。

**Comment by lunnlew** [comment]
临时方案可以在 include 中 增加 "node_modules/baidu-map-vue3/**/*.d.ts"

**Comment by lunnlew** [comment]
问题修复,   可更新到版本 [0.4.3](https://www.npmjs.com/package/baidu-map-vue3/v/0.4.3)

**Comment by xwnwho** [comment]
![image](https://user-images.githubusercontent.com/80031313/154632093-c418c1b2-9084-4c95-98bb-b5a249dd5f5d.png)
我这边tsconfig设置了noImplicitAny": false，数组如果不声明类型，默认是never[]

**Comment by lunnlew** [comment]
错误修复于 0.4.5
