### ISSUE TITLE
Marker 添加label属性，报错

### ISSUE THREAD

**Issue by xwnwho** [lunnlew/baidu-map#8]
this._config.label.setPoint is not a function

**Comment by lunnlew** [comment]
看起来应该是label未实例化完成就进行位置改变导致报错，可以提供下代码片段么

**Comment by lunnlew** [comment]
label属性的问题应该修复了，更新至0.4.6， 作用域插槽问题是怎样的不正常？

**Comment by xwnwho** [comment]
label 问题好了，polyline的问题我重新提个issue
